# Generated by Django 3.0.5 on 2020-05-06 16:51

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.TextField(max_length=20)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Customer ID')),
                ('first_name', models.CharField(max_length=65, verbose_name='First name')),
                ('last_name', models.CharField(max_length=65, verbose_name='Last name')),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('e_mail', models.EmailField(max_length=65, verbose_name='E-mail')),
                ('address', models.CharField(max_length=65, verbose_name='Address')),
                ('city', models.CharField(max_length=65, verbose_name='City')),
                ('zip', models.CharField(max_length=6, verbose_name='Zip code')),
                ('company', models.CharField(max_length=240, null=True, verbose_name='Company')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Suspended'), (3, 'Inactive'), (4, 'VIP')], default='1', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tax', models.IntegerField(choices=[(1, 0.0), (2, 0.05), (3, 0.08), (4, 0.23)])),
                ('invoices_days', models.IntegerField(choices=[(1, 14), (2, 30), (3, 60)])),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10240)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product_stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordertoline', to='Clients.Order')),
                ('product_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Product')),
                ('unit_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordertoprice', to='Clients.Product')),
            ],
        ),
    ]
