# Generated by Django 3.0.5 on 2020-05-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_category_customer_order_orderline_product_textbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Open'), (3, 'Suspended'), (4, 'Canceled')], default=1),
            preserve_default=False,
        ),
    ]
