# Generated by Django 3.0.5 on 2020-05-06 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
