# Generated by Django 3.0.5 on 2020-05-06 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_auto_20200506_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, message='Price must be above 0.1')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Enter number greater or equal to 1')]),
        ),
    ]
