# Generated by Django 3.0.5 on 2020-05-06 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0009_auto_20200506_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimum quantity = 1')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10, message='Minimum value = 10')]),
        ),
    ]
