# Generated by Django 3.0.5 on 2020-05-06 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0010_auto_20200506_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='Minimum value = 10')]),
        ),
    ]
