# Generated by Django 3.0.5 on 2020-05-06 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0011_auto_20200506_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='unit_price',
        ),
    ]
