# Generated by Django 3.0.5 on 2020-05-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0013_orderline_product_selected_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Open'), (3, 'Suspended'), (4, 'Canceled'), (5, 'Closed')]),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product_selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Product', verbose_name='Product'),
        ),
    ]
