# Generated by Django 3.0.5 on 2020-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0015_customer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(default='https:/', null=True),
        ),
    ]
